In [6]:
import pandas as pd

### 1. 연령별 인구현황 검색 excel파일 저장
 ### 2. 상단 3개를 삭제후 가져오기
 ### 3. 행정기관 index 지정
 ### 4. 상단 5개만 출력하시오.

In [7]:
df = pd.read_excel('20240514인구.xlsx',skiprows=3,index_col='행정기관',\
    usecols='b,e:y') #usecols= 사용할 컬럼
# df.set_index('행정기관')
df.columns
df
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '20240514인구.xlsx'

In [22]:
w_df = pd.read_excel('202301_인구.xlsx',skiprows=3,index_col='행정기관',\
    usecols='b,ab:av') #usecols= 사용할 컬럼
# df.set_index('행정기관')
w_df.columns = df.columns # 컬럼 내용이 다르지만 같게 맞춰준다
w_df.columns
w_df
w_df.head()
# w_df.head()

c:\Users\KOREAVC\AppData\Local\Programs\Python\Python311\Lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,0~4세,5~9세,10~14세,15~19세,20~24세,25~29세,30~34세,35~39세,40~44세,45~49세,...,55~59세,60~64세,65~69세,70~74세,75~79세,80~84세,85~89세,90~94세,95~99세,100세 이상
행정기관,,,,,,,,,,,,,,,,,,,,,
전국,"691,045","1,020,598","1,144,645","1,134,811","1,402,493","1,642,682","1,579,871","1,598,401","1,980,502","1,990,483",...,"2,017,243","2,132,394","1,649,709","1,174,486","908,877","802,501","459,932","177,039","39,806","6,604"
서울특별시,"109,390","154,162","176,096","189,009","304,285","418,972","379,071","333,112","368,850","362,938",...,"352,068","375,498","310,677","221,007","169,985","127,276","66,321","25,368","6,162","1,043"
부산광역시,"39,356","60,582","65,329","64,001","88,307","102,363","96,466","95,847","123,903","120,997",...,"135,400","160,060","134,634","99,254","70,537","56,380","28,523","10,347","2,375",337
대구광역시,"29,517","47,039","51,645","53,188","65,933","71,873","65,115","66,014","89,451","94,571",...,"101,480","104,047","80,241","60,862","42,860","37,331","20,068","7,062","1,418",216
인천광역시,"41,505","59,985","66,881","65,904","80,089","99,535","98,125","96,427","118,715","116,262",...,"122,949","124,904","89,016","57,046","44,221","36,855","21,193","8,813","2,089",360

In [2]:
# rows 데이터 가져오기
# df[0:3]
# df.head(3)
# df.tail(2)
# df[df.columns[-1]] # 맨 뒤의 칼럼

df.iloc[0] # 0번째 rows 데이터 가져오기
df.iloc[0].str # str로 타입 변경
df.iloc[0].str.replace(",","").astype(int) # 쉼표제거, astype(int): 정수형으로 변경
df.iloc[0] = df.iloc[0].str.replace(",","").astype(int) # 0번째 데이터를, 쉼표제거, astype(int): 정수형으로 변경
df.info()

NameError: name 'df' is not defined

In [12]:
df.iloc[0]

0~4세        726460
5~9세       1072653
10~14세     1211077
15~19세     1211949
20~24세     1524378
25~29세     1823908
30~34세     1737714
35~39세     1684266
40~44세     2055130
45~49세     2039606
50~54세     2303096
55~59세     2052227
60~64세     2097254
65~69세     1554976
70~74세     1038388
75~79세      713448
80~84세      507915
85~89세      212726
90~94세       54180
95~99세        8880
100세 이상       1307
Name: 전국  , dtype: object